# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_executor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='remote_executor.proto',
    package='server',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x15remote_executor.proto\x12\x06server\"(\n\x0b\x44\x61taRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"2\n\x0c\x44\x61taResponse\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\x12\x10\n\x08user_num\x18\x02 \x01(\x05\x32I\n\x0eRemoteExecutor\x12\x37\n\x08SendData\x12\x13.server.DataRequest\x1a\x14.server.DataResponse\"\x00\x62\x06proto3'
)

_DATAREQUEST = _descriptor.Descriptor(
    name='DataRequest',
    full_name='server.DataRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='uid',
            full_name='server.DataRequest.uid',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='data',
            full_name='server.DataRequest.data',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=33,
    serialized_end=73, )

_DATARESPONSE = _descriptor.Descriptor(
    name='DataResponse',
    full_name='server.DataResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='err_code',
            full_name='server.DataResponse.err_code',
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='user_num',
            full_name='server.DataResponse.user_num',
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=75,
    serialized_end=125, )

DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['DataResponse'] = _DATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataRequest = _reflection.GeneratedProtocolMessageType(
    'DataRequest',
    (_message.Message, ),
    {
        'DESCRIPTOR': _DATAREQUEST,
        '__module__': 'remote_executor_pb2'
        # @@protoc_insertion_point(class_scope:server.DataRequest)
    })
_sym_db.RegisterMessage(DataRequest)

DataResponse = _reflection.GeneratedProtocolMessageType(
    'DataResponse',
    (_message.Message, ),
    {
        'DESCRIPTOR': _DATARESPONSE,
        '__module__': 'remote_executor_pb2'
        # @@protoc_insertion_point(class_scope:server.DataResponse)
    })
_sym_db.RegisterMessage(DataResponse)

_REMOTEEXECUTOR = _descriptor.ServiceDescriptor(
    name='RemoteExecutor',
    full_name='server.RemoteExecutor',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=127,
    serialized_end=200,
    methods=[
        _descriptor.MethodDescriptor(
            name='SendData',
            full_name='server.RemoteExecutor.SendData',
            index=0,
            containing_service=None,
            input_type=_DATAREQUEST,
            output_type=_DATARESPONSE,
            serialized_options=None, ),
    ])
_sym_db.RegisterServiceDescriptor(_REMOTEEXECUTOR)

DESCRIPTOR.services_by_name['RemoteExecutor'] = _REMOTEEXECUTOR

# @@protoc_insertion_point(module_scope)
