// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package masterpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProcStatus int32

const (
	ProcStatus_INITIAL        ProcStatus = 0
	ProcStatus_PART_PROCESSED ProcStatus = 1
	ProcStatus_PROCESSED      ProcStatus = 2
)

var ProcStatus_name = map[int32]string{
	0: "INITIAL",
	1: "PART_PROCESSED",
	2: "PROCESSED",
}

var ProcStatus_value = map[string]int32{
	"INITIAL":        0,
	"PART_PROCESSED": 1,
	"PROCESSED":      2,
}

func (x ProcStatus) String() string {
	return proto.EnumName(ProcStatus_name, int32(x))
}

func (ProcStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type RPCRet struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCRet) Reset()         { *m = RPCRet{} }
func (m *RPCRet) String() string { return proto.CompactTextString(m) }
func (*RPCRet) ProtoMessage()    {}
func (*RPCRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *RPCRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRet.Unmarshal(m, b)
}
func (m *RPCRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRet.Marshal(b, m, deterministic)
}
func (m *RPCRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRet.Merge(m, src)
}
func (m *RPCRet) XXX_Size() int {
	return xxx_messageInfo_RPCRet.Size(m)
}
func (m *RPCRet) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRet.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRet proto.InternalMessageInfo

func (m *RPCRet) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RPCRet) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type Trainer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trainer) Reset()         { *m = Trainer{} }
func (m *Trainer) String() string { return proto.CompactTextString(m) }
func (*Trainer) ProtoMessage()    {}
func (*Trainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Trainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trainer.Unmarshal(m, b)
}
func (m *Trainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trainer.Marshal(b, m, deterministic)
}
func (m *Trainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trainer.Merge(m, src)
}
func (m *Trainer) XXX_Size() int {
	return xxx_messageInfo_Trainer.Size(m)
}
func (m *Trainer) XXX_DiscardUnknown() {
	xxx_messageInfo_Trainer.DiscardUnknown(m)
}

var xxx_messageInfo_Trainer proto.InternalMessageInfo

type POD struct {
	Trainers             []*Trainer `protobuf:"bytes,1,rep,name=trainers,proto3" json:"trainers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *POD) Reset()         { *m = POD{} }
func (m *POD) String() string { return proto.CompactTextString(m) }
func (*POD) ProtoMessage()    {}
func (*POD) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *POD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POD.Unmarshal(m, b)
}
func (m *POD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POD.Marshal(b, m, deterministic)
}
func (m *POD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POD.Merge(m, src)
}
func (m *POD) XXX_Size() int {
	return xxx_messageInfo_POD.Size(m)
}
func (m *POD) XXX_DiscardUnknown() {
	xxx_messageInfo_POD.DiscardUnknown(m)
}

var xxx_messageInfo_POD proto.InternalMessageInfo

func (m *POD) GetTrainers() []*Trainer {
	if m != nil {
		return m.Trainers
	}
	return nil
}

type Cluster struct {
	JobFlag              string   `protobuf:"bytes,1,opt,name=job_flag,json=jobFlag,proto3" json:"job_flag,omitempty"`
	Pods                 []*POD   `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetJobFlag() string {
	if m != nil {
		return m.JobFlag
	}
	return ""
}

func (m *Cluster) GetPods() []*POD {
	if m != nil {
		return m.Pods
	}
	return nil
}

type ClusterResponse struct {
	Ret                  *RPCRet  `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Cluster              *Cluster `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterResponse) Reset()         { *m = ClusterResponse{} }
func (m *ClusterResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterResponse) ProtoMessage()    {}
func (*ClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *ClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterResponse.Unmarshal(m, b)
}
func (m *ClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterResponse.Marshal(b, m, deterministic)
}
func (m *ClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterResponse.Merge(m, src)
}
func (m *ClusterResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterResponse.Size(m)
}
func (m *ClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterResponse proto.InternalMessageInfo

func (m *ClusterResponse) GetRet() *RPCRet {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *ClusterResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type ClusterRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterRequest) Reset()         { *m = ClusterRequest{} }
func (m *ClusterRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterRequest) ProtoMessage()    {}
func (*ClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *ClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterRequest.Unmarshal(m, b)
}
func (m *ClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterRequest.Marshal(b, m, deterministic)
}
func (m *ClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterRequest.Merge(m, src)
}
func (m *ClusterRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterRequest.Size(m)
}
func (m *ClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterRequest proto.InternalMessageInfo

func (m *ClusterRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type ShutDownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutDownRequest) Reset()         { *m = ShutDownRequest{} }
func (m *ShutDownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutDownRequest) ProtoMessage()    {}
func (*ShutDownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *ShutDownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutDownRequest.Unmarshal(m, b)
}
func (m *ShutDownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutDownRequest.Marshal(b, m, deterministic)
}
func (m *ShutDownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutDownRequest.Merge(m, src)
}
func (m *ShutDownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutDownRequest.Size(m)
}
func (m *ShutDownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutDownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutDownRequest proto.InternalMessageInfo

type RecordRangeStatus struct {
	Status               ProcStatus `protobuf:"varint,1,opt,name=status,proto3,enum=common.ProcStatus" json:"status,omitempty"`
	Begin                int64      `protobuf:"varint,2,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  int64      `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RecordRangeStatus) Reset()         { *m = RecordRangeStatus{} }
func (m *RecordRangeStatus) String() string { return proto.CompactTextString(m) }
func (*RecordRangeStatus) ProtoMessage()    {}
func (*RecordRangeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *RecordRangeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordRangeStatus.Unmarshal(m, b)
}
func (m *RecordRangeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordRangeStatus.Marshal(b, m, deterministic)
}
func (m *RecordRangeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRangeStatus.Merge(m, src)
}
func (m *RecordRangeStatus) XXX_Size() int {
	return xxx_messageInfo_RecordRangeStatus.Size(m)
}
func (m *RecordRangeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRangeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRangeStatus proto.InternalMessageInfo

func (m *RecordRangeStatus) GetStatus() ProcStatus {
	if m != nil {
		return m.Status
	}
	return ProcStatus_INITIAL
}

func (m *RecordRangeStatus) GetBegin() int64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *RecordRangeStatus) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type RecordRange struct {
	Begin                int64    `protobuf:"varint,2,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  int64    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordRange) Reset()         { *m = RecordRange{} }
func (m *RecordRange) String() string { return proto.CompactTextString(m) }
func (*RecordRange) ProtoMessage()    {}
func (*RecordRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *RecordRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordRange.Unmarshal(m, b)
}
func (m *RecordRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordRange.Marshal(b, m, deterministic)
}
func (m *RecordRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRange.Merge(m, src)
}
func (m *RecordRange) XXX_Size() int {
	return xxx_messageInfo_RecordRange.Size(m)
}
func (m *RecordRange) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRange.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRange proto.InternalMessageInfo

func (m *RecordRange) GetBegin() int64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *RecordRange) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterEnum("common.ProcStatus", ProcStatus_name, ProcStatus_value)
	proto.RegisterType((*RPCRet)(nil), "common.RPCRet")
	proto.RegisterType((*Trainer)(nil), "common.Trainer")
	proto.RegisterType((*POD)(nil), "common.POD")
	proto.RegisterType((*Cluster)(nil), "common.Cluster")
	proto.RegisterType((*ClusterResponse)(nil), "common.ClusterResponse")
	proto.RegisterType((*ClusterRequest)(nil), "common.ClusterRequest")
	proto.RegisterType((*ShutDownRequest)(nil), "common.ShutDownRequest")
	proto.RegisterType((*RecordRangeStatus)(nil), "common.RecordRangeStatus")
	proto.RegisterType((*RecordRange)(nil), "common.RecordRange")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x8f, 0x93, 0x40,
	0x14, 0x97, 0xb2, 0x0b, 0xdb, 0xc7, 0x4a, 0xbb, 0x2f, 0x6a, 0xf0, 0x64, 0x33, 0x17, 0xd7, 0x9a,
	0xf4, 0x80, 0x7a, 0xd2, 0x4b, 0x2d, 0x35, 0x21, 0x31, 0x96, 0x0c, 0x3d, 0x79, 0xb0, 0xe1, 0x63,
	0x44, 0x1a, 0xca, 0x20, 0x33, 0xc4, 0xf8, 0xdf, 0x1b, 0x86, 0xa1, 0xed, 0xd1, 0xdb, 0xfb, 0xf8,
	0x7d, 0xbd, 0xc9, 0xc0, 0x7d, 0xc6, 0x4f, 0x27, 0x5e, 0xaf, 0x9a, 0x96, 0x4b, 0x8e, 0xd6, 0xd0,
	0x91, 0xf7, 0x60, 0xd1, 0x68, 0x43, 0x99, 0x44, 0x84, 0x1b, 0xf9, 0xb7, 0x61, 0x9e, 0xb1, 0x30,
	0x1e, 0xa7, 0x54, 0xd5, 0xf8, 0x02, 0xac, 0x9c, 0xc9, 0xa4, 0xac, 0xbc, 0x89, 0x9a, 0xea, 0x8e,
	0x4c, 0xc1, 0xde, 0xb7, 0x49, 0x59, 0xb3, 0x96, 0xf8, 0x60, 0x46, 0xbb, 0x00, 0xdf, 0xc2, 0x9d,
	0x1c, 0x26, 0xc2, 0x33, 0x16, 0xe6, 0xa3, 0xe3, 0xcf, 0x56, 0xda, 0x50, 0x23, 0xe9, 0x19, 0x40,
	0xb6, 0x60, 0x6f, 0xaa, 0x4e, 0x48, 0xd6, 0xe2, 0x4b, 0xb8, 0x3b, 0xf2, 0xf4, 0xf0, 0xb3, 0x4a,
	0x0a, 0xed, 0x6c, 0x1f, 0x79, 0xfa, 0xa5, 0x4a, 0x0a, 0x7c, 0x05, 0x37, 0x0d, 0xcf, 0x85, 0x37,
	0x51, 0x72, 0xce, 0x28, 0x17, 0xed, 0x02, 0xaa, 0x16, 0xe4, 0x07, 0xcc, 0xb4, 0x0c, 0x65, 0xa2,
	0xe1, 0xb5, 0x60, 0xb8, 0x00, 0xb3, 0x65, 0x52, 0x29, 0x39, 0xbe, 0x3b, 0x52, 0x86, 0x0b, 0x69,
	0xbf, 0xc2, 0x37, 0x60, 0x67, 0x03, 0x49, 0xdd, 0x74, 0x95, 0x73, 0xd4, 0x1a, 0xf7, 0xe4, 0x35,
	0xb8, 0x67, 0xfd, 0xdf, 0x1d, 0x13, 0x12, 0x9f, 0x83, 0xd5, 0xa7, 0x2d, 0x73, 0x9d, 0xf5, 0xf6,
	0xc8, 0xd3, 0x30, 0x27, 0x0f, 0x30, 0x8b, 0x7f, 0x75, 0x32, 0xe0, 0x7f, 0x6a, 0x8d, 0x24, 0x05,
	0x3c, 0x50, 0x96, 0xf1, 0x36, 0xa7, 0x49, 0x5d, 0xb0, 0x58, 0x26, 0xb2, 0x13, 0xb8, 0x04, 0x4b,
	0xa8, 0x4a, 0xd1, 0x5d, 0x1f, 0xcf, 0x37, 0xb5, 0x3c, 0x1b, 0x30, 0x54, 0x23, 0xf0, 0x19, 0xdc,
	0xa6, 0xac, 0x28, 0x6b, 0x95, 0xd2, 0xa4, 0x43, 0x83, 0x73, 0x30, 0x59, 0x9d, 0x7b, 0xa6, 0x9a,
	0xf5, 0x25, 0xf9, 0x00, 0xce, 0x95, 0xd1, 0xff, 0xd2, 0x96, 0x9f, 0x00, 0x2e, 0xa6, 0xe8, 0x80,
	0x1d, 0x7e, 0x0b, 0xf7, 0xe1, 0xfa, 0xeb, 0xfc, 0x09, 0x22, 0xb8, 0xd1, 0x9a, 0xee, 0x0f, 0x11,
	0xdd, 0x6d, 0xb6, 0x71, 0xbc, 0x0d, 0xe6, 0x06, 0x3e, 0x85, 0xe9, 0xa5, 0x9d, 0x7c, 0xbe, 0xff,
	0x0e, 0xab, 0x8f, 0xa7, 0xa4, 0x7f, 0x9a, 0x26, 0x4d, 0x2d, 0xf5, 0xa5, 0xde, 0xfd, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x15, 0x07, 0x18, 0xf9, 0x62, 0x02, 0x00, 0x00,
}
