# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_pb2 as common__pb2
import compute_server_pb2 as compute__server__pb2


class ComputeServerStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.DoTasksByFilesMeta = channel.unary_unary(
            '/compute_server.ComputeServer/DoTasksByFilesMeta',
            request_serializer=compute__server__pb2.FilesMetaRequest.
            SerializeToString,
            response_deserializer=common__pb2.RPCRet.FromString, )
        self.SetTaskProgramDesc = channel.unary_unary(
            '/compute_server.ComputeServer/SetTaskProgramDesc',
            request_serializer=common__pb2.Program.SerializeToString,
            response_deserializer=common__pb2.RPCRet.FromString, )


class ComputeServerServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def DoTasksByFilesMeta(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTaskProgramDesc(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'DoTasksByFilesMeta': grpc.unary_unary_rpc_method_handler(
            servicer.DoTasksByFilesMeta,
            request_deserializer=compute__server__pb2.FilesMetaRequest.
            FromString,
            response_serializer=common__pb2.RPCRet.SerializeToString, ),
        'SetTaskProgramDesc': grpc.unary_unary_rpc_method_handler(
            servicer.SetTaskProgramDesc,
            request_deserializer=common__pb2.Program.FromString,
            response_serializer=common__pb2.RPCRet.SerializeToString, ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'compute_server.ComputeServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler, ))
