# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import common_pb2 as common__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='data_server.proto',
    package='data_server',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x11\x64\x61ta_server.proto\x12\x0b\x64\x61ta_server\x1a\x0c\x63ommon.proto\"7\n\x0fMetaDataRequest\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\x12\x10\n\x08step_num\x18\x02 \x01(\x05\"B\n\nDataReader\x12\x13\n\x0b\x64\x61ta_reader\x18\x01 \x01(\t\x12\x1f\n\x04meta\x18\x02 \x01(\x0b\x32\x11.common.FilesMeta\"Y\n\x10MetaDataResponse\x12\x1b\n\x03ret\x18\x01 \x01(\x0b\x32\x0e.common.RPCRet\x12(\n\x07readers\x18\x02 \x03(\x0b\x32\x17.data_server.DataReader\" \n\x0c\x45pochRequest\x12\x10\n\x08\x65poch_no\x18\x01 \x01(\t\"\x13\n\x11\x44\x61taSourceRequest2\xce\x02\n\nDataServer\x12:\n\x12\x41ssignDataResource\x12\x12.common.DataSource\x1a\x0e.common.RPCRet\"\x00\x12\x37\n\x08NewEpoch\x12\x19.data_server.EpochRequest\x1a\x0e.common.RPCRet\"\x00\x12L\n\x0bGetMetaData\x12\x1c.data_server.MetaDataRequest\x1a\x1d.data_server.MetaDataResponse\"\x00\x12\x45\n\rGetDataSource\x12\x1e.data_server.DataSourceRequest\x1a\x12.common.DataSource\"\x00\x12\x36\n\x0fReportFilesMeta\x12\x11.common.FilesMeta\x1a\x0e.common.RPCRet\"\x00\x62\x06proto3',
    dependencies=[common__pb2.DESCRIPTOR, ])

_METADATAREQUEST = _descriptor.Descriptor(
    name='MetaDataRequest',
    full_name='data_server.MetaDataRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='batch_size',
            full_name='data_server.MetaDataRequest.batch_size',
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='step_num',
            full_name='data_server.MetaDataRequest.step_num',
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=48,
    serialized_end=103, )

_DATAREADER = _descriptor.Descriptor(
    name='DataReader',
    full_name='data_server.DataReader',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='data_reader',
            full_name='data_server.DataReader.data_reader',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='meta',
            full_name='data_server.DataReader.meta',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=105,
    serialized_end=171, )

_METADATARESPONSE = _descriptor.Descriptor(
    name='MetaDataResponse',
    full_name='data_server.MetaDataResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='ret',
            full_name='data_server.MetaDataResponse.ret',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='readers',
            full_name='data_server.MetaDataResponse.readers',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=173,
    serialized_end=262, )

_EPOCHREQUEST = _descriptor.Descriptor(
    name='EpochRequest',
    full_name='data_server.EpochRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='epoch_no',
            full_name='data_server.EpochRequest.epoch_no',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=264,
    serialized_end=296, )

_DATASOURCEREQUEST = _descriptor.Descriptor(
    name='DataSourceRequest',
    full_name='data_server.DataSourceRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=298,
    serialized_end=317, )

_DATAREADER.fields_by_name['meta'].message_type = common__pb2._FILESMETA
_METADATARESPONSE.fields_by_name['ret'].message_type = common__pb2._RPCRET
_METADATARESPONSE.fields_by_name['readers'].message_type = _DATAREADER
DESCRIPTOR.message_types_by_name['MetaDataRequest'] = _METADATAREQUEST
DESCRIPTOR.message_types_by_name['DataReader'] = _DATAREADER
DESCRIPTOR.message_types_by_name['MetaDataResponse'] = _METADATARESPONSE
DESCRIPTOR.message_types_by_name['EpochRequest'] = _EPOCHREQUEST
DESCRIPTOR.message_types_by_name['DataSourceRequest'] = _DATASOURCEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaDataRequest = _reflection.GeneratedProtocolMessageType(
    'MetaDataRequest',
    (_message.Message, ),
    {
        'DESCRIPTOR': _METADATAREQUEST,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_server.MetaDataRequest)
    })
_sym_db.RegisterMessage(MetaDataRequest)

DataReader = _reflection.GeneratedProtocolMessageType(
    'DataReader',
    (_message.Message, ),
    {
        'DESCRIPTOR': _DATAREADER,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_server.DataReader)
    })
_sym_db.RegisterMessage(DataReader)

MetaDataResponse = _reflection.GeneratedProtocolMessageType(
    'MetaDataResponse',
    (_message.Message, ),
    {
        'DESCRIPTOR': _METADATARESPONSE,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_server.MetaDataResponse)
    })
_sym_db.RegisterMessage(MetaDataResponse)

EpochRequest = _reflection.GeneratedProtocolMessageType(
    'EpochRequest',
    (_message.Message, ),
    {
        'DESCRIPTOR': _EPOCHREQUEST,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_server.EpochRequest)
    })
_sym_db.RegisterMessage(EpochRequest)

DataSourceRequest = _reflection.GeneratedProtocolMessageType(
    'DataSourceRequest',
    (_message.Message, ),
    {
        'DESCRIPTOR': _DATASOURCEREQUEST,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_server.DataSourceRequest)
    })
_sym_db.RegisterMessage(DataSourceRequest)

_DATASERVER = _descriptor.ServiceDescriptor(
    name='DataServer',
    full_name='data_server.DataServer',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=320,
    serialized_end=654,
    methods=[
        _descriptor.MethodDescriptor(
            name='AssignDataResource',
            full_name='data_server.DataServer.AssignDataResource',
            index=0,
            containing_service=None,
            input_type=common__pb2._DATASOURCE,
            output_type=common__pb2._RPCRET,
            serialized_options=None, ),
        _descriptor.MethodDescriptor(
            name='NewEpoch',
            full_name='data_server.DataServer.NewEpoch',
            index=1,
            containing_service=None,
            input_type=_EPOCHREQUEST,
            output_type=common__pb2._RPCRET,
            serialized_options=None, ),
        _descriptor.MethodDescriptor(
            name='GetMetaData',
            full_name='data_server.DataServer.GetMetaData',
            index=2,
            containing_service=None,
            input_type=_METADATAREQUEST,
            output_type=_METADATARESPONSE,
            serialized_options=None, ),
        _descriptor.MethodDescriptor(
            name='GetDataSource',
            full_name='data_server.DataServer.GetDataSource',
            index=3,
            containing_service=None,
            input_type=_DATASOURCEREQUEST,
            output_type=common__pb2._DATASOURCE,
            serialized_options=None, ),
        _descriptor.MethodDescriptor(
            name='ReportFilesMeta',
            full_name='data_server.DataServer.ReportFilesMeta',
            index=4,
            containing_service=None,
            input_type=common__pb2._FILESMETA,
            output_type=common__pb2._RPCRET,
            serialized_options=None, ),
    ])
_sym_db.RegisterServiceDescriptor(_DATASERVER)

DESCRIPTOR.services_by_name['DataServer'] = _DATASERVER

# @@protoc_insertion_point(module_scope)
