# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='common.proto',
    package='common',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\",\n\x06RPCRet\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\x12\x10\n\x08\x65rr_info\x18\x02 \x01(\x05\"\t\n\x07Trainer\"(\n\x03POD\x12!\n\x08trainers\x18\x01 \x03(\x0b\x32\x0f.common.Trainer\"6\n\x07\x43luster\x12\x10\n\x08job_flag\x18\x01 \x01(\t\x12\x19\n\x04pods\x18\x02 \x03(\x0b\x32\x0b.common.POD\"P\n\x0f\x43lusterResponse\x12\x1b\n\x03ret\x18\x01 \x01(\x0b\x32\x0e.common.RPCRet\x12 \n\x07\x63luster\x18\x02 \x01(\x0b\x32\x0f.common.Cluster\" \n\x0e\x43lusterRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\x11\n\x0fShutDownRequestb\x06proto3'
)

_RPCRET = _descriptor.Descriptor(
    name='RPCRet',
    full_name='common.RPCRet',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='err_code',
            full_name='common.RPCRet.err_code',
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='err_info',
            full_name='common.RPCRet.err_info',
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=24,
    serialized_end=68, )

_TRAINER = _descriptor.Descriptor(
    name='Trainer',
    full_name='common.Trainer',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=70,
    serialized_end=79, )

_POD = _descriptor.Descriptor(
    name='POD',
    full_name='common.POD',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='trainers',
            full_name='common.POD.trainers',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=81,
    serialized_end=121, )

_CLUSTER = _descriptor.Descriptor(
    name='Cluster',
    full_name='common.Cluster',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='job_flag',
            full_name='common.Cluster.job_flag',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='pods',
            full_name='common.Cluster.pods',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=123,
    serialized_end=177, )

_CLUSTERRESPONSE = _descriptor.Descriptor(
    name='ClusterResponse',
    full_name='common.ClusterResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='ret',
            full_name='common.ClusterResponse.ret',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cluster',
            full_name='common.ClusterResponse.cluster',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=179,
    serialized_end=259, )

_CLUSTERREQUEST = _descriptor.Descriptor(
    name='ClusterRequest',
    full_name='common.ClusterRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='job_id',
            full_name='common.ClusterRequest.job_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=261,
    serialized_end=293, )

_SHUTDOWNREQUEST = _descriptor.Descriptor(
    name='ShutDownRequest',
    full_name='common.ShutDownRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=295,
    serialized_end=312, )

_POD.fields_by_name['trainers'].message_type = _TRAINER
_CLUSTER.fields_by_name['pods'].message_type = _POD
_CLUSTERRESPONSE.fields_by_name['ret'].message_type = _RPCRET
_CLUSTERRESPONSE.fields_by_name['cluster'].message_type = _CLUSTER
DESCRIPTOR.message_types_by_name['RPCRet'] = _RPCRET
DESCRIPTOR.message_types_by_name['Trainer'] = _TRAINER
DESCRIPTOR.message_types_by_name['POD'] = _POD
DESCRIPTOR.message_types_by_name['Cluster'] = _CLUSTER
DESCRIPTOR.message_types_by_name['ClusterResponse'] = _CLUSTERRESPONSE
DESCRIPTOR.message_types_by_name['ClusterRequest'] = _CLUSTERREQUEST
DESCRIPTOR.message_types_by_name['ShutDownRequest'] = _SHUTDOWNREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPCRet = _reflection.GeneratedProtocolMessageType(
    'RPCRet',
    (_message.Message, ),
    {
        'DESCRIPTOR': _RPCRET,
        '__module__': 'common_pb2'
        # @@protoc_insertion_point(class_scope:common.RPCRet)
    })
_sym_db.RegisterMessage(RPCRet)

Trainer = _reflection.GeneratedProtocolMessageType(
    'Trainer',
    (_message.Message, ),
    {
        'DESCRIPTOR': _TRAINER,
        '__module__': 'common_pb2'
        # @@protoc_insertion_point(class_scope:common.Trainer)
    })
_sym_db.RegisterMessage(Trainer)

POD = _reflection.GeneratedProtocolMessageType(
    'POD',
    (_message.Message, ),
    {
        'DESCRIPTOR': _POD,
        '__module__': 'common_pb2'
        # @@protoc_insertion_point(class_scope:common.POD)
    })
_sym_db.RegisterMessage(POD)

Cluster = _reflection.GeneratedProtocolMessageType(
    'Cluster',
    (_message.Message, ),
    {
        'DESCRIPTOR': _CLUSTER,
        '__module__': 'common_pb2'
        # @@protoc_insertion_point(class_scope:common.Cluster)
    })
_sym_db.RegisterMessage(Cluster)

ClusterResponse = _reflection.GeneratedProtocolMessageType(
    'ClusterResponse',
    (_message.Message, ),
    {
        'DESCRIPTOR': _CLUSTERRESPONSE,
        '__module__': 'common_pb2'
        # @@protoc_insertion_point(class_scope:common.ClusterResponse)
    })
_sym_db.RegisterMessage(ClusterResponse)

ClusterRequest = _reflection.GeneratedProtocolMessageType(
    'ClusterRequest',
    (_message.Message, ),
    {
        'DESCRIPTOR': _CLUSTERREQUEST,
        '__module__': 'common_pb2'
        # @@protoc_insertion_point(class_scope:common.ClusterRequest)
    })
_sym_db.RegisterMessage(ClusterRequest)

ShutDownRequest = _reflection.GeneratedProtocolMessageType(
    'ShutDownRequest',
    (_message.Message, ),
    {
        'DESCRIPTOR': _SHUTDOWNREQUEST,
        '__module__': 'common_pb2'
        # @@protoc_insertion_point(class_scope:common.ShutDownRequest)
    })
_sym_db.RegisterMessage(ShutDownRequest)

# @@protoc_insertion_point(module_scope)
