# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_pb2 as common__pb2
import data_server_pb2 as data__server__pb2


class DataServerStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.GetData = channel.unary_unary(
            '/data_reader.DataServer/GetData',
            request_serializer=data__server__pb2.DataRequest.SerializeToString,
            response_deserializer=data__server__pb2.DataResponse.FromString, )
        self.ClearDataCache = channel.unary_unary(
            '/data_reader.DataServer/ClearDataCache',
            request_serializer=data__server__pb2.DataRequest.SerializeToString,
            response_deserializer=common__pb2.RPCRet.FromString, )
        self.ShutDown = channel.unary_unary(
            '/data_reader.DataServer/ShutDown',
            request_serializer=common__pb2.ShutDownRequest.SerializeToString,
            response_deserializer=common__pb2.RPCRet.FromString, )


class DataServerServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetData(self, request, context):
        """loader -> DataSet
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearDataCache(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutDown(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetData': grpc.unary_unary_rpc_method_handler(
            servicer.GetData,
            request_deserializer=data__server__pb2.DataRequest.FromString,
            response_serializer=data__server__pb2.DataResponse.
            SerializeToString, ),
        'ClearDataCache': grpc.unary_unary_rpc_method_handler(
            servicer.ClearDataCache,
            request_deserializer=data__server__pb2.DataRequest.FromString,
            response_serializer=common__pb2.RPCRet.SerializeToString, ),
        'ShutDown': grpc.unary_unary_rpc_method_handler(
            servicer.ShutDown,
            request_deserializer=common__pb2.ShutDownRequest.FromString,
            response_serializer=common__pb2.RPCRet.SerializeToString, ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'data_reader.DataServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler, ))
