# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_server.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import common_pb2 as common__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='data_server.proto',
    package='data_reader',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x11\x64\x61ta_server.proto\x12\x0b\x64\x61ta_reader\x1a\x0c\x63ommon.proto\")\n\x06Record\x12\x11\n\trecord_no\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"T\n\x04\x46ile\x12\x13\n\x0bidx_in_list\x18\x01 \x01(\x03\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12$\n\x07records\x18\x03 \x03(\x0b\x32\x13.data_reader.Record\")\n\x05\x46iles\x12 \n\x05\x66iles\x18\x01 \x03(\x0b\x32\x11.data_reader.File\"I\n\x0bRecordError\x12\x11\n\trecord_no\x18\x01 \x01(\x03\x12\'\n\x06status\x18\x02 \x01(\x0e\x32\x17.data_reader.DataStatus\"\x86\x01\n\tFileError\x12\x13\n\x0bidx_in_list\x18\x01 \x01(\x03\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\'\n\x06status\x18\x03 \x01(\x0e\x32\x17.data_reader.DataStatus\x12(\n\x06\x65rrors\x18\x04 \x03(\x0b\x32\x18.data_reader.RecordError\"4\n\nFilesError\x12&\n\x06\x65rrors\x18\x01 \x03(\x0b\x32\x16.data_reader.FileError\"Z\n\x0c\x44\x61taResponse\x12\'\n\x06\x65rrors\x18\x01 \x01(\x0b\x32\x17.data_reader.FilesError\x12!\n\x05\x66iles\x18\x02 \x01(\x0b\x32\x12.data_reader.Files\"E\n\x08\x44\x61taMeta\x12\x13\n\x0bidx_in_list\x18\x01 \x01(\x03\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x11\n\trecord_no\x18\x03 \x03(\x03\"3\n\x0b\x44\x61taRequest\x12$\n\x05metas\x18\x01 \x03(\x0b\x32\x15.data_reader.DataMeta*(\n\nDataStatus\x12\x0b\n\x07\x44\x41TA_OK\x10\x00\x12\r\n\tNOT_FOUND\x10\x01\x32\xc3\x01\n\nDataServer\x12@\n\x07GetData\x12\x18.data_reader.DataRequest\x1a\x19.data_reader.DataResponse\"\x00\x12<\n\x0e\x43learDataCache\x12\x18.data_reader.DataRequest\x1a\x0e.common.RPCRet\"\x00\x12\x35\n\x08ShutDown\x12\x17.common.ShutDownRequest\x1a\x0e.common.RPCRet\"\x00\x62\x06proto3',
    dependencies=[common__pb2.DESCRIPTOR, ])

_DATASTATUS = _descriptor.EnumDescriptor(
    name='DataStatus',
    full_name='data_reader.DataStatus',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='DATA_OK',
            index=0,
            number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='NOT_FOUND',
            index=1,
            number=1,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=702,
    serialized_end=742, )
_sym_db.RegisterEnumDescriptor(_DATASTATUS)

DataStatus = enum_type_wrapper.EnumTypeWrapper(_DATASTATUS)
DATA_OK = 0
NOT_FOUND = 1

_RECORD = _descriptor.Descriptor(
    name='Record',
    full_name='data_reader.Record',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='record_no',
            full_name='data_reader.Record.record_no',
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='data',
            full_name='data_reader.Record.data',
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=48,
    serialized_end=89, )

_FILE = _descriptor.Descriptor(
    name='File',
    full_name='data_reader.File',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='idx_in_list',
            full_name='data_reader.File.idx_in_list',
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='file_path',
            full_name='data_reader.File.file_path',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='records',
            full_name='data_reader.File.records',
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=91,
    serialized_end=175, )

_FILES = _descriptor.Descriptor(
    name='Files',
    full_name='data_reader.Files',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='files',
            full_name='data_reader.Files.files',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=177,
    serialized_end=218, )

_RECORDERROR = _descriptor.Descriptor(
    name='RecordError',
    full_name='data_reader.RecordError',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='record_no',
            full_name='data_reader.RecordError.record_no',
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='status',
            full_name='data_reader.RecordError.status',
            index=1,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=220,
    serialized_end=293, )

_FILEERROR = _descriptor.Descriptor(
    name='FileError',
    full_name='data_reader.FileError',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='idx_in_list',
            full_name='data_reader.FileError.idx_in_list',
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='file_path',
            full_name='data_reader.FileError.file_path',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='status',
            full_name='data_reader.FileError.status',
            index=2,
            number=3,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='errors',
            full_name='data_reader.FileError.errors',
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=296,
    serialized_end=430, )

_FILESERROR = _descriptor.Descriptor(
    name='FilesError',
    full_name='data_reader.FilesError',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='errors',
            full_name='data_reader.FilesError.errors',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=432,
    serialized_end=484, )

_DATARESPONSE = _descriptor.Descriptor(
    name='DataResponse',
    full_name='data_reader.DataResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='errors',
            full_name='data_reader.DataResponse.errors',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='files',
            full_name='data_reader.DataResponse.files',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=486,
    serialized_end=576, )

_DATAMETA = _descriptor.Descriptor(
    name='DataMeta',
    full_name='data_reader.DataMeta',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='idx_in_list',
            full_name='data_reader.DataMeta.idx_in_list',
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='file_path',
            full_name='data_reader.DataMeta.file_path',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='record_no',
            full_name='data_reader.DataMeta.record_no',
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=578,
    serialized_end=647, )

_DATAREQUEST = _descriptor.Descriptor(
    name='DataRequest',
    full_name='data_reader.DataRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='metas',
            full_name='data_reader.DataRequest.metas',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=649,
    serialized_end=700, )

_FILE.fields_by_name['records'].message_type = _RECORD
_FILES.fields_by_name['files'].message_type = _FILE
_RECORDERROR.fields_by_name['status'].enum_type = _DATASTATUS
_FILEERROR.fields_by_name['status'].enum_type = _DATASTATUS
_FILEERROR.fields_by_name['errors'].message_type = _RECORDERROR
_FILESERROR.fields_by_name['errors'].message_type = _FILEERROR
_DATARESPONSE.fields_by_name['errors'].message_type = _FILESERROR
_DATARESPONSE.fields_by_name['files'].message_type = _FILES
_DATAREQUEST.fields_by_name['metas'].message_type = _DATAMETA
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Files'] = _FILES
DESCRIPTOR.message_types_by_name['RecordError'] = _RECORDERROR
DESCRIPTOR.message_types_by_name['FileError'] = _FILEERROR
DESCRIPTOR.message_types_by_name['FilesError'] = _FILESERROR
DESCRIPTOR.message_types_by_name['DataResponse'] = _DATARESPONSE
DESCRIPTOR.message_types_by_name['DataMeta'] = _DATAMETA
DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.enum_types_by_name['DataStatus'] = _DATASTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Record = _reflection.GeneratedProtocolMessageType(
    'Record',
    (_message.Message, ),
    {
        'DESCRIPTOR': _RECORD,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_reader.Record)
    })
_sym_db.RegisterMessage(Record)

File = _reflection.GeneratedProtocolMessageType(
    'File',
    (_message.Message, ),
    {
        'DESCRIPTOR': _FILE,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_reader.File)
    })
_sym_db.RegisterMessage(File)

Files = _reflection.GeneratedProtocolMessageType(
    'Files',
    (_message.Message, ),
    {
        'DESCRIPTOR': _FILES,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_reader.Files)
    })
_sym_db.RegisterMessage(Files)

RecordError = _reflection.GeneratedProtocolMessageType(
    'RecordError',
    (_message.Message, ),
    {
        'DESCRIPTOR': _RECORDERROR,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_reader.RecordError)
    })
_sym_db.RegisterMessage(RecordError)

FileError = _reflection.GeneratedProtocolMessageType(
    'FileError',
    (_message.Message, ),
    {
        'DESCRIPTOR': _FILEERROR,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_reader.FileError)
    })
_sym_db.RegisterMessage(FileError)

FilesError = _reflection.GeneratedProtocolMessageType(
    'FilesError',
    (_message.Message, ),
    {
        'DESCRIPTOR': _FILESERROR,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_reader.FilesError)
    })
_sym_db.RegisterMessage(FilesError)

DataResponse = _reflection.GeneratedProtocolMessageType(
    'DataResponse',
    (_message.Message, ),
    {
        'DESCRIPTOR': _DATARESPONSE,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_reader.DataResponse)
    })
_sym_db.RegisterMessage(DataResponse)

DataMeta = _reflection.GeneratedProtocolMessageType(
    'DataMeta',
    (_message.Message, ),
    {
        'DESCRIPTOR': _DATAMETA,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_reader.DataMeta)
    })
_sym_db.RegisterMessage(DataMeta)

DataRequest = _reflection.GeneratedProtocolMessageType(
    'DataRequest',
    (_message.Message, ),
    {
        'DESCRIPTOR': _DATAREQUEST,
        '__module__': 'data_server_pb2'
        # @@protoc_insertion_point(class_scope:data_reader.DataRequest)
    })
_sym_db.RegisterMessage(DataRequest)

_DATASERVER = _descriptor.ServiceDescriptor(
    name='DataServer',
    full_name='data_reader.DataServer',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=745,
    serialized_end=940,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetData',
            full_name='data_reader.DataServer.GetData',
            index=0,
            containing_service=None,
            input_type=_DATAREQUEST,
            output_type=_DATARESPONSE,
            serialized_options=None, ),
        _descriptor.MethodDescriptor(
            name='ClearDataCache',
            full_name='data_reader.DataServer.ClearDataCache',
            index=1,
            containing_service=None,
            input_type=_DATAREQUEST,
            output_type=common__pb2._RPCRET,
            serialized_options=None, ),
        _descriptor.MethodDescriptor(
            name='ShutDown',
            full_name='data_reader.DataServer.ShutDown',
            index=2,
            containing_service=None,
            input_type=common__pb2._SHUTDOWNREQUEST,
            output_type=common__pb2._RPCRET,
            serialized_options=None, ),
    ])
_sym_db.RegisterServiceDescriptor(_DATASERVER)

DESCRIPTOR.services_by_name['DataServer'] = _DATASERVER

# @@protoc_insertion_point(module_scope)
